Remove destination table from BigQuery config
thoth-station/prescriptions-refresh-job pull request #171
Opened 2022-06-15 12:17 UTC by mayaCostantini

## This introduces a breaking change

- No

## This should yield a new module release

- Yes

## This Pull Request implements

Remove BigQuery job configuration and destination table.

2022-06-15 12:17 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mayacostantini** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fprescriptions-refresh-job).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/prescriptions-refresh-job/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mayacostantini"]} -->

2022-06-15 13:09 UTC, codificat requested changes
Nit: currently the PR is a one line change but there are 2 commits; better squash them into 1.

Besides that, this LGTM, but I must admit I'm not sure I get its purpose :innocent:   could you elaborate a bit on the context/why?
Thanks!

2022-06-15 14:44 UTC, mayaCostantini commented
@codificat thanks for the review, I updated the PR description and squashed the commits

2022-06-17 04:23 UTC, harshad16 approved these changes
/lgtm
/approve

2022-06-17 04:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/prescriptions-refresh-job/pull/171#pullrequestreview-1009981562" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fprescriptions-refresh-job).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/prescriptions-refresh-job/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-06-17 04:28 UTC, merged